#!/bin/bash

# Check for correct number of arguments
if [ "$#" -ne 1 ]; then
    echo "You must enter exactly 1 command line argument."
    echo "Use the '-help' option to see options!"
    exit 1
fi

if [ $1 == "-help" ]; then
    echo "Use 'install' to install requirements, <url_file> to run on urls, or 'test' to run tests!"
elif [ $1 == "install" ]; then
    python3 -m venv .
    source ./bin/activate
    pip3 install --upgrade pip
    pip3 install -r requirements.txt
    deactivate
elif [[ $1 == *.txt ]]; then
    source ./bin/activate
    python3 main.py $1
    deactivate
elif [[ $1 == "test" ]]; then
    source ./bin/activate
    > test_output.txt
    coverage run -m pytest test.py >> test_output.txt
    coverage report -m >> test_output.txt
    python3 print_tests.py test_output.txt
    deactivate
elif [[ $1 == "clean" ]]; then
    echo "Cleaning install..."
    rm -r __pycache__
    rm -r .pytest_cache
    rm -r bin
    rm -r include
    rm -r lib
    rm -r repo_clone
    rm -r share
    rm project-1-24.log
    rm pyvenv.cfg
else
    echo "Invalid command line argument"
    echo "Use the '-help' option to see options!"
    exit 1
fi

exit 0
