# This is a basic workflow to help you get started with Actions

name: Project 2 REST API Testing (CI)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Python 3.7.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.5"
          
      - name: Installing Dependencies
        run: |
          pip3 install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt
          gcloud components install cloud-datastore-emulator beta --quiet
          
      - name: Running PyTest
        run: |
          gcloud beta emulators datastore start --data-dir=tests/datastore --quiet && 
          sleep 10 && 
          gcloud beta emulators datastore env-init &&
          sleep 10 &&
          python main.py &&
          sleep 10 &&
          pytest tests/

#       - name: Deploy to App Engine
#         run: gcloud app deploy --quiet
