# This is a basic workflow to help you get started with Actions

name: Project 2 Deployment (CD)

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        
      - name: Use gcloud CLI
        run: gcloud info
          
      - name: Set up Python 3.7.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.5"
          
      - name: Installing Dependencies
        run: |
          pip3 install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt
          gcloud components install cloud-datastore-emulator beta --quiet
          
      - name: Running PyTest
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud beta emulators datastore start --data-dir=tests/datastore --quiet &
          sleep 10
          python main.py &
          sleep 10
          coverage run -m pytest tests/ && coverage report -m
          
      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
