# Upon pushes and pull requests into main, this workflow will run our test suite

name: Continuous Integration testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOG_LEVEL: 0
      LOG_FILE: actions_test.log
    
    steps:
    - uses: actions/checkout@v2
          
    - name: Confirming environment variables
      run: |
        echo GITHUB_TOKEN length: ${#GITHUB_TOKEN}
        echo LOG_LEVEL: ${LOG_LEVEL}
        echo LOG_FILE: ${LOG_FILE}
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.6.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # install dependencies
        pip install -r package_rating/requirements.txt
        coverage run -m pytest package_rating/test.py
        coverage report -m