# Upon pushes and pull requests into main, this workflow will run our test suite

name: Continuous Integration testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOG_LEVEL: 0
      LOG_FILE: actions_test.log
    
    steps:
    - uses: actions/checkout@v2
          
    - name: Confirming Environment Variables
      run: |
        echo GITHUB_TOKEN length: ${#GITHUB_TOKEN}
        echo LOG_LEVEL: ${LOG_LEVEL}
        echo LOG_FILE: ${LOG_FILE}
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.6.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_api_requests/package_rating/requirements.txt

    - name: Test with PyTest
      run: |
        coverage run -m pytest app_api_requests/package_rating/test.py
        coverage report -m
